### ISSUE TITLE
Value Error on the plot_audio.py

### ISSUE THREAD

**Issue by truongbylaclam** [AssemblyAI-Examples/python-speech-recognition-course#1]
I tried to run the plot audio using the source code and it produce this error.
![image](https://user-images.githubusercontent.com/24442118/173914024-79d20490-d95c-4f0e-b3df-397c0f145a7c.png)

All the module version and Python is updated.

**Comment by NovemberFalls** [comment]
I am having this issue as well.

**Comment by ploeber** [comment]
Looks like signal_array has 3x as many elements as times. The easiest way to fix this is by setting

```
times = np.linspace(0, n_samples/sample_freq, num=n_samples*3)
```

However, I would try to figure out the root of the problem. E.g., if signal_array has multiple channels (Stereo), you must filter out and plot only the separate channels. Also you could check the sample width with obj.getsampwidth() and see if this is affecting the calculations

**Comment by setthawut8** [comment]
try the @ploeber 's solution and it works well.

**Comment by setthawut8** [comment]
> Looks like signal_array has 3x as many elements as times. The easiest way to fix this is by setting
> 
> ```
> times = np.linspace(0, n_samples/sample_freq, num=n_samples*3)
> ```
> 
> However, I would try to figure out the root of the problem. E.g., if signal_array has multiple channels (Stereo), you must filter out and plot only the separate channels. Also you could check the sample width with obj.getsampwidth() and see if this is affecting the calculations


I tried the @ploeber 's solution and it works well.
